"""Add vehicle type, log status

Revision ID: 377e203c909a
Revises: b229a053386d
Create Date: 2022-01-05 16:22:45.341262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377e203c909a'
down_revision = 'b229a053386d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_file', sa.Column('processing_status', sa.String(), nullable=True))
    op.alter_column('log_file', 'upload_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('vehicle', sa.Column('vehicle_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'vehicle_type')
    op.alter_column('log_file', 'upload_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('log_file', 'processing_status')
    # ### end Alembic commands ###
