"""add hidden flag and headline

Revision ID: 44226898f2fa
Revises: bea116b19867
Create Date: 2022-11-30 08:58:28.614687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44226898f2fa'
down_revision = 'bea116b19867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_file', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('log_file', sa.Column('hide_in_web', sa.Boolean(), nullable=True))
    op.execute("UPDATE log_file SET hide_in_web = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_file', 'hide_in_web')
    op.drop_column('log_file', 'headline')
    # ### end Alembic commands ###
