"""initial

Revision ID: ed85969596e7
Revises: 
Create Date: 2025-09-02 14:35:07.058937

"""
from alembic import op
import sqlalchemy as sa

from database.models import TZNaiveDateTime


# revision identifiers, used by Alembic.
revision = 'ed85969596e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('unit_number')
    )
    op.create_table('log_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_number', sa.Integer(), nullable=False),
    sa.Column('log_start_time', TZNaiveDateTime(), nullable=True),
    sa.Column('log_end_time', TZNaiveDateTime(), nullable=True),
    sa.Column('upload_time', TZNaiveDateTime(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('length_sec', sa.Float(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('original_file_name', sa.String(), nullable=True),
    sa.Column('file_stem', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('hide_in_web', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unit_number'], ['vehicle.unit_number'], name='vehicle_id_log_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_number', 'log_number', name='uq_unit_log_number')
    )
    op.create_table('log_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log_file.id'], name='comment_log_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_comment')
    op.drop_table('log_file')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
